---
keepalived_config: |
  global_defs {
    vrrp_version 3
    vrrp_strict
    max_auto_priority
    vrrp_priority -20
    checker_priority -20
    bfd_priority -20
    vrrp_no_swap
    checker_no_swap
    bfd_no_swap
    reload_check_config
  }
...
